export default {
  ADD_NOTE: "ADD_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  SET_NOTES: "SET_NOTES",
  LOAD_NOTES: "LOAD_NOTES",
  SET_INPUT_TITLE: "SET_INPUT_TITLE",
  SET_INPUT_CONTENT: "SET_INPUT_CONTENT",
  SET_INPUT_ID: "SET_INPUT_ID",
  SET_ID: "SET_ID",
  RESET_INPUT: "RESET_INPUT",
};
